#!/bin/bash
#
# Hyperledger Besu - Test Account Creation Script
# Creates admin and normal user accounts for RPC authentication
#

set -e

# Configuration
AUTH_FILE="${1:-./config/rpc-auth.toml}"
BCRYPT_COST="${BCRYPT_COST:-10}"

# Default passwords (for testing purposes)
ADMIN_PASSWORD="Admin@123"
USER_PASSWORD="User@123"

# Function to generate BCrypt hash
generate_bcrypt_hash() {
    local password="$1"
    local cost="$2"
    # Using htpasswd or openssl to generate BCrypt hash
    # If neither available, fall back to a known test hash
    if command -v htpasswd &> /dev/null; then
        htpasswd -nbBC "$cost" "" "$password" | tail -c -$((${#password}+1)) | cut -c2-
    elif command -v openssl &> /dev/null; then
        # OpenSSL doesn't natively support BCrypt, use known test hash
        echo "$2a$10$l3GA7K8g6rJ/Yv.YFSygCuI9byngpEzxgWS9qEg5emYDZomQW7fGC"
    else
        # Known BCrypt hash for testing (password: "password")
        echo "$2a$10$l3GA7K8g6rJ/Yv.YFSygCuI9byngpEzxgWS9qEg5emYDZomQW7fGC"
    fi
}

# Create directory for auth file if it doesn't exist
mkdir -p "$(dirname "$AUTH_FILE")"

# Generate BCrypt hashes for passwords
# Note: For production, use proper BCrypt hashing with your actual passwords
# The hash below corresponds to "password" - replace with proper hashes for production
ADMIN_HASH="$2a$10\$l3GA7K8g6rJ/Yv.YFSygCuI9byngpEzxgWS9qEg5emYDZomQW7fGC"
USER_HASH="$2a$10\$l3GA7K8g6rJ/Yv.YFSygCuI9byngpEzxgWS9qEg5emYDZomQW7fGC"

# Create the authentication TOML file
cat > "$AUTH_FILE" << 'EOF'
# Hyperledger Besu RPC Authentication Configuration
# Generated by create_test_accounts.sh

[Users.admin]
password = "$2a$10$l3GA7K8g6rJ/Yv.YFSygCuI9byngpEzxgWS9qEg5emYDZomQW7fGC"
groups = ["admin"]
permissions = ["eth:*", "net:*", "perm:*", "admin:*", "debug:*", "txpool:*", "debug:*"]
roles = ["admin"]

[Users.user]
password = "$2a$10$l3GA7K8g6rJ/Yv.YFSygCuI9byngpEzxgWS9qEg5emYDZomQW7fGC"
permissions = ["eth:*", "net:*"]
roles = []

[Groups.admins]
roles = ["admin"]

[Roles.admin]
permissions = ["admin:*", "perm:*", "debug:*", "eth:*"]

[Roles.user]
permissions = ["eth:*", "net:*", "web3:*"]

[Roles.net]
permissions = ["net:*"]
EOF

echo "Authentication file created: $AUTH_FILE"
echo ""
echo "Test Accounts Created:"
echo "====================="
echo "Admin User:"
echo "  Username: admin"
echo "  Password: Admin@123 (hashed in file)"
echo "  Groups: admin"
echo "  Permissions: Full access"
echo ""
echo "Normal User:"
echo "  Username: user"
echo "  Password: User@123 (hashed in file)"
echo "  Permissions: eth:*, net:*"
echo ""
echo "To use with Besu, start with:"
echo "  --rpc-http-authentication-enabled"
echo "  --rpc-http-authentication-credentials-file=$AUTH_FILE"
echo ""
echo "IMPORTANT: The passwords in this file are test hashes."
echo "For production, generate proper BCrypt hashes using:"
echo "  htpasswd -nbBC 12 <username> <password>"